import Vue from 'vue';
import 'element-ui/lib/theme-chalk/display.css';
import {
  Pagination,
  Dialog,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Menu,
  Submenu,
  MenuItem,
  MenuItemGroup,
  Input,
  Radio,
  RadioGroup,
  RadioButton,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Switch,
  Select,
  Option,
  OptionGroup,
  Button,
  ButtonGroup,
  Link,
  Table,
  TableColumn,
  DatePicker,
  TimeSelect,
  TimePicker,
  Popover,
  Tooltip,
  Form,
  FormItem,
  Tabs,
  TabPane,
  Alert,
  Icon,
  Row,
  Col,
  Upload,
  Spinner,
  Badge,
  Card,
  Steps,
  Step,
  Carousel,
  CarouselItem,
  Collapse,
  CollapseItem,
  Cascader,
  ColorPicker,
  Container,
  Header,
  Aside,
  Main,
  Footer,
  Timeline,
  TimelineItem,
  Divider,
  Image,
  Backtop,
  Loading,
  MessageBox,
  Message,
  Notification,
  Tree,
  InputNumber,
  Scrollbar,
  Breadcrumb,
  BreadcrumbItem,
  Tag,
} from 'element-ui';

Vue.use(Pagination)
  .use(Dialog)
  .use(Dropdown)
  .use(DropdownMenu)
  .use(DropdownItem)
  .use(Menu)
  .use(Submenu)
  .use(MenuItem)
  .use(MenuItemGroup)
  .use(Input)
  .use(Radio)
  .use(RadioGroup)
  .use(RadioButton)
  .use(Checkbox)
  .use(CheckboxButton)
  .use(CheckboxGroup)
  .use(Switch)
  .use(Select)
  .use(Option)
  .use(OptionGroup)
  .use(Button)
  .use(ButtonGroup)
  .use(Link)
  .use(Table)
  .use(TableColumn)
  .use(DatePicker)
  .use(TimeSelect)
  .use(TimePicker)
  .use(Popover)
  .use(Tooltip)
  .use(Form)
  .use(FormItem)
  .use(Tabs)
  .use(TabPane)
  .use(Alert)
  .use(Icon)
  .use(Row)
  .use(Col)
  .use(Upload)
  .use(Spinner)
  .use(Badge)
  .use(Card)
  .use(Steps)
  .use(Step)
  .use(Carousel)
  .use(CarouselItem)
  .use(Collapse)
  .use(CollapseItem)
  .use(Cascader)
  .use(ColorPicker)
  .use(Container)
  .use(Header)
  .use(Aside)
  .use(Main)
  .use(Footer)
  .use(Timeline)
  .use(TimelineItem)
  .use(Divider)
  .use(Image)
  .use(Backtop)
  .use(Tree)
  .use(InputNumber)
  .use(Scrollbar)
  .use(Breadcrumb)
  .use(BreadcrumbItem)
  .use(Tag)
  .use(Loading.directive);


Vue.prototype.$loading = Loading.service;
Vue.prototype.$msgbox = MessageBox;
Vue.prototype.$alert = MessageBox.alert;
Vue.prototype.$confirm = MessageBox.confirm;
Vue.prototype.$prompt = MessageBox.prompt;
Vue.prototype.$notify = Notification;
Vue.prototype.$message = Message;
